// GENERATED by `npm run db:schema -- --update` from supabase/schema.snapshot.txt (the schema the
// migrations build, which CI keeps identical to production's). Do not edit by hand. Numeric columns
// arrive from PostgREST as JSON numbers, and nullable columns as null.

/** A row of public.transactions. */
export interface TransactionRow {
  account_number: string;
  amount_naira: number;
  amount_usdt: number;
  api_response: string | null;
  blockchain: string | null;
  client_ip: string | null;
  contact_details: string | null;
  country_code: string | null;
  created_at: string;
  customer_address: string | null;
  customer_email: string | null;
  customer_name: string | null;
  discount_campaign_id: string | null;
  discount_ngn: number;
  discount_phone: string | null;
  display_amount: string | null;
  error_code: string | null;
  fee_naira: number;
  foreign_amount: number | null;
  id: string;
  meter_account_type: string | null;
  network: string;
  operator_id: string | null;
  payment_method: string | null;
  phone: string | null;
  product_type_id: string | null;
  purchased_code: string | null;
  refund_hash: string | null;
  request_id: string | null;
  service_category: string;
  service_id: string | null;
  source_channel: string | null;
  stamp_duty_ngn: number | null;
  status: string;
  subscription_type: string | null;
  token_used: string | null;
  tx_hash: string;
  units: string | null;
  variation_code: string | null;
  vend_dispatched_at: string | null;
  wallet_address: string;
  x402_nonce: string | null;
  x402_payer: string | null;
  x402_settle_tx: string | null;
  x402_valid_before: string | null;
}

/** A row of public.refund_queue. */
export interface RefundQueueRow {
  amount_crypto: number;
  amount_naira: number | null;
  approved_at: string | null;
  approved_by: string | null;
  blockchain: string;
  completed_at: string | null;
  created_at: string;
  id: string;
  notes: string | null;
  reason: string;
  refund_tx_hash: string | null;
  service_category: string | null;
  source_channel: string | null;
  status: string;
  token_used: string;
  transaction_id: string | null;
  tx_hash: string;
  user_notified: boolean;
  vtpass_error: string | null;
  wallet_address: string;
}

/** A row of public.discount_campaigns. */
export interface DiscountCampaignRow {
  created_at: string;
  created_by: string | null;
  ends_at: string | null;
  id: string;
  is_active: boolean;
  max_discount_ngn: number | null;
  max_discount_per_destination_ngn: number | null;
  max_discount_per_phone_ngn: number | null;
  max_discount_per_wallet_ngn: number | null;
  max_total_discount_ngn: number | null;
  name: string;
  services: string[] | null;
  starts_at: string | null;
  type: string;
  updated_at: string;
  value: number;
}

/** A row of public.scheduled_bills. */
export interface ScheduledBillRow {
  amount_ngn: number;
  auto_execute: boolean;
  batch_id: string | null;
  billers_code: string;
  blockchain: string | null;
  consecutive_failures: number;
  created_at: string;
  customer_address: string | null;
  customer_name: string | null;
  day_of_month: number | null;
  day_of_week: number | null;
  frequency: string;
  id: string;
  is_active: boolean;
  last_notified_at: string | null;
  last_paid_at: string | null;
  last_run_date: string | null;
  last_tx_hash: string | null;
  meter_type: string | null;
  notify_channel: string | null;
  notify_channel_id: string | null;
  notify_email: string | null;
  notify_telegram: string | null;
  provider: string | null;
  run_once_at: string | null;
  service_category: string;
  service_id: string;
  token_used: string | null;
  variation_code: string | null;
  wallet_address: string;
}
