// Generates src/lib/rows.ts (TypeScript row shapes for the payment tables) from the schema
// snapshot, so the types the code relies on can't drift from the database. Owned by
// scripts/db-schema.mjs: `--update` rewrites it, the check fails if it's stale.

export const ROW_TYPES_FILE = 'src/lib/rows.ts';

const TABLES = [
  ['transactions', 'TransactionRow', 'A row of public.transactions.'],
  ['refund_queue', 'RefundQueueRow', 'A row of public.refund_queue.'],
];

export function rowTypesFromSnapshot(snapshot) {
  const columns = {};
  for (const line of snapshot.split(/\r?\n/)) {
    const m = line.match(/^column (\w+)\.(\w+) (.+)$/);
    if (!m) continue;
    const [, table, column, rest] = m;
    const sqlType = rest.replace(/ not null.*| default .*/, '').trim();
    const ts = /^numeric/.test(sqlType) ? 'number' : sqlType === 'boolean' ? 'boolean' : 'string';
    (columns[table] ??= []).push(`  ${column}: ${ts}${/ not null/.test(rest) ? '' : ' | null'};`);
  }
  const blocks = TABLES.map(([table, name, doc]) => `/** ${doc} */\nexport interface ${name} {\n${columns[table].join('\n')}\n}\n`);
  return `// GENERATED by \`npm run db:schema -- --update\` from supabase/schema.snapshot.txt (the schema the
// migrations build, which CI keeps identical to production's). Do not edit by hand. Numeric columns
// arrive from PostgREST as JSON numbers, and nullable columns as null.

${blocks.join('\n')}`;
}
